### ISSUE TITLE
Changelog from Eclipser 1.0?

### ISSUE THREAD

**Issue by gustavo-grieco** [SoftSec-KAIST/Eclipser#10]
I'm wondering if you can give some details regarding the recent changes included in Eclipser 1.0 release since the commit is quite large.

**Comment by jchoi2022** [comment]
Yes, I am sorry for the large commit, and such thing will not happen again from now on.
Also, I will provide a changelog for the updates in v1.0, soon.

**Comment by jchoi2022** [comment]
In in e24fd963, I added a brief change log for the updates in v1.0 release.

**Comment by gustavo-grieco** [comment]
Thanks!
