### ISSUE TITLE
Understand the output directory

### ISSUE THREAD

**Issue by andreafioraldi** [SoftSec-KAIST/Eclipser#11]
Hi,
I'm trying to fuzz tcpdump with Eclipse and I don't understand the purpose of the testcase directory in the output directory.
After 15 min of fuzzing there is only a testcase `tc-0` inside the directory.
The starting input is uninformed, 72 `0` (ascii).

Eclipse doesn't log inputs that trigger new coverage?

**Comment by andreafioraldi** [comment]
My command is
`dotnet ~/Eclipser/build/Eclipser.dll fuzz -p ./tcpdump -v 1 -i zero_in -t 86400 -o out/tcpdump/eclipser/ --src file --initarg "-nr /tmp/tcpdump.input" -f /tmp/tcpdump.input`

**Comment by jchoi2022** [comment]
Hi,

Eclipser will save found test cases (that covered new nodes) into the output directory. I tried the described command on my Ubuntu 16.04 machine, and Eclipser found about 30 test cases within one minute. I used the tcpdump binary pre-installed in my Ubuntu, and its version is as follow.

```$ tcpdump --version
tcpdump version 4.9.2
libpcap version 1.7.4
OpenSSL 1.0.2g  1 Mar 2016
```

Maybe you might have tried a wrong command-line for tcpdump (for example, before edit, you were providing '--input' option to tcpdump). In such cases, Eclipser cannot find any meaningful test case.

If you compiled your own tcpdump binary from source files, I will take a look if you tell me which source files you used, and which command you used to configure and build tcpdump.

**Comment by andreafioraldi** [comment]
Thanks you anyway was my fault, seems that I've compiled tcpdump under Ubuntu and it crashes when using library code in QEMU on my old Debian fuzzing setup (AFL Qemu continuosly reports crashes). The command line is right, I rewrote it from scratch for the issue here copying the template from the README.
