### ISSUE TITLE
TCG instrumentation?

### ISSUE THREAD

**Issue by neuromancer** [SoftSec-KAIST/Eclipser#6]
I wonder if the [TCG instrumentation patches](https://abiondo.me/2018/09/21/improving-afl-qemu-mode/) are used in Eclipser (I believe they are not). They seem to give a good performance improvement (3x/4x according to its author).

**Comment by jchoi2022** [comment]
Thank you for introducing an interesting post! As you said, the patches are not used in current Eclipser. I will take a look into the code and check if it is applicable to Eclipser.

**Comment by jchoi2022** [comment]
I finally had some time to take a look into this issue. Commit 4f31203c29669ea6349cf4848b8dd41a49021574 adopts the patches from the blog post to Eclipser. Also, I confirmed a significant improvement in performance. Thank you for providing useful information, and I apologize for taking so long to address the issue.
