### ISSUE TITLE
Sampling input bytes instead of conditional statements in SELECT?

### ISSUE THREAD

**Issue by neuromancer** [SoftSec-KAIST/Eclipser#7]
According to the paper: 

> SELECT randomly  selects N conditional  statements  from  the  given  sequence  of conditional  statements.

However, instead of selecting N randomly conditional statements, I'm wondering if you have tried to **randomly selecting inputs bytes to generate conditional statements**. In that case, the results will be (most likely) less or simpler conditions to solve but without the risk of finding unfeasible solutions. You could even select input bytes using different sampling distributions (uniform, or by ranges)

**Comment by jchoi2022** [comment]
So, I think your question is about how we select byte values, when mutating a certain input byte in SPAWN function (please correct me if I misunderstood).

Currently, Eclipser samples input byte values uniformly from the given interval (recall that each byte is accompanied with an approximate constraint represented in an interval form). Then, Eclipser generates distinct seeds by replacing the input byte with sampled values. By executing program with these seeds, Eclipser observes affected conditional statements, and choose N of them.

And I'm sorry but I did not exactly catch your point in: 

> the results will be less or simpler conditions to solve

Could you elaborate about what is the baseline that you are comparing against?

Please let me know if I misunderstood your point. Thanks!

**Comment by neuromancer** [comment]
After a discussion with @sangkilc, he clarified that this approach is not effective on real programs.
