### ISSUE TITLE
Allow the user to select the arquitecture to compile

### ISSUE THREAD

**Issue by gustavo-grieco** [SoftSec-KAIST/Eclipser#9]
Eclipser takes quite a long time to compile, since it recompiles QEMU for i386 and x64, however usually the user needs only one them. Is it possible to add a flag in the Makefile to compile for only one of these?

**Comment by jchoi2022** [comment]
This seems to be a good idea. I will fix Makefile so one can build Eclipser for specific architecture, with `make x86` and `make x64`.

**Comment by jchoi2022** [comment]
I updated build scripts and Makefile in ce47d08a5. Now one can run `make x86` or `make x64` to specify target architecture, which reduces QEMU build time. Running `make` will build QEMU for both architectures.

Note that even if you run `make x64`, running `make` in the next time will try to build QEMU for x86 architecture. Therefore, you should stick to `make x64` in the subsequent builds, too. Actually this hassle can be avoided with a little fix, but it will make our Makefile somewhat hacky.

**Comment by gustavo-grieco** [comment]
Thanks!
